### PR TITLE
Updates to helm chart versions for upgrading kubernetes to 1.25.

### PR DESCRIPTION
**Pull request by dhirajshettymoj**
## What does this pull request do?

Updates to helm chart versions for upgrading kubernetes to 1.25.
## What is the intent behind these changes?

Updates to helm chart versions for upgrading kubernetes to 1.25.

### CODE REVIEW

**Review by AledWEvans — APPROVED** [review]
LGTM

**Comment by dhirajshettymoj** [comment]
can you please re-review. I have added the security fixes too as part of the same commit (by error).

**Review by AledWEvans — DISMISSED** [review]
LGTM

**Comment by dhirajshettymoj** [comment]
removed code that was incorrectly checked in against this PR.

**Pull request merged**
